# Generated by Django 3.0.3 on 2020-02-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200215_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='',
            name='stripe_charge_id',
            field=models.CharField(max_length=50),
        ),
    ]
