# Generated by Django 3.0.3 on 2020-02-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persons',
        ),
    ]
