# Generated by Django 3.0.3 on 2020-02-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200218_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='image', upload_to=''),
            preserve_default=False,
        ),
    ]
